# Generated by Django 5.0.6 on 2024-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de la hora extra')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, help_text='Número de horas trabajadas', max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor de las horas trabajadas', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHoraRecargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_hora_recargo', models.CharField(choices=[('extra_diurno', 'Extra diurno'), ('trabajo_extra_nocturno', 'Trabajo extra nocturno'), ('trabajo_extra_diurno_dominical_festivo', 'Trabajo extra diurno dominical y festivo'), ('trabajo_extra_nocturno_dominical_festivo', 'Trabajo extra nocturno en domingos y festivos'), ('trabajo_nocturno', 'Trabajo nocturno'), ('trabajo_dominical_festivo', 'Trabajo dominical y festivo'), ('trabajo_nocturno_dominical_festivo', 'Trabajo nocturno en dominical y festivo')], help_text='Tipo de hora con recargo', max_length=50)),
                ('porc_hora_recargo', models.DecimalField(decimal_places=2, help_text='Porcentaje del recargo de la hora', max_digits=5)),
            ],
        ),
    ]
