# Generated by Django 5.0.6 on 2024-06-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devengos', '0001_initial'),
        ('gestion_empleados', '0002_empleado_nivel_riesgo_empleado_salario_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='nro_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.empleado'),
        ),
        migrations.AddField(
            model_name='tipohorarecargo',
            name='nro_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.empleado'),
        ),
    ]
