# Generated by Django 5.0.6 on 2024-06-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devengos', '0003_alter_tipohorarecargo_tipo_hora_recargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohorarecargo',
            name='nro_documento',
        ),
    ]
