# Generated by Django 5.0.6 on 2024-06-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devengos', '0004_remove_tipohorarecargo_nro_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaextra',
            name='horas_trabajadas',
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horaEd',
            field=models.IntegerField(blank=True, help_text='Horas Extra diurna', null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horaEdd',
            field=models.IntegerField(blank=True, help_text='Horas Extra diurna dominical', null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horaEn',
            field=models.IntegerField(blank=True, help_text='Horas Extra nocturna', null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horaEnd',
            field=models.IntegerField(blank=True, help_text='Horas Extra nocturna dominical', null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='recargoD',
            field=models.IntegerField(blank=True, help_text='Recargo dominical', null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='recargoN',
            field=models.IntegerField(blank=True, help_text='Recargo nocturno', null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='recargoNd',
            field=models.IntegerField(blank=True, help_text='Recargo nocturno dominical', null=True),
        ),
    ]
