# Generated by Django 5.0.6 on 2024-06-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devengos', '0005_remove_horaextra_horas_trabajadas_horaextra_horaed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaextra',
            name='valor',
        ),
        migrations.AddField(
            model_name='horaextra',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total de las horas trabajadas', max_digits=10, null=True),
        ),
    ]
