# Generated by Django 5.0.6 on 2024-06-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devengos', '0006_remove_horaextra_valor_horaextra_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horaextra',
            name='horaEd',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='horaEdd',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='horaEn',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='horaEnd',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='recargoD',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='recargoN',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='recargoNd',
        ),
        migrations.RemoveField(
            model_name='horaextra',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='horaextra',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Número de horas trabajadas', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='horaextra',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de las horas trabajadas', max_digits=10, null=True),
        ),
    ]
