# Generated by Django 5.0.6 on 2024-06-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devengos', '0007_remove_horaextra_horaed_remove_horaextra_horaedd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='tipo_Hora',
            field=models.ManyToManyField(null=True, to='devengos.tipohorarecargo'),
        ),
    ]
