# Generated by Django 5.0.6 on 2024-06-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deducciones', '0001_initial'),
        ('gestion_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguridadsocial',
            name='nro_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='nivelriesgo',
            name='nivel_riesgo',
            field=models.CharField(choices=[('1', 'Riesgo I'), ('2', 'Riesgo II'), ('3', 'Riesgo III'), ('4', 'Riesgo IV'), ('5', 'Riesgo V')], help_text='Nivel de riesgo', max_length=100),
        ),
    ]
