# Generated by Django 5.0.6 on 2024-06-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deducciones', '0006_alter_seguridadsocial_empleado_delete_empleado'),
        ('gestion_empleados', '0009_alter_empleado_nivel_riesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelriesgo',
            name='porcentaje_nivel',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje del nivel de riesgo', max_digits=5),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='empleado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_social', to='gestion_empleados.empleado'),
            preserve_default=False,
        ),
    ]
