# Generated by Django 5.0.6 on 2024-06-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deducciones', '0007_alter_nivelriesgo_porcentaje_nivel_and_more'),
        ('gestion_empleados', '0009_alter_empleado_nivel_riesgo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.PositiveIntegerField()),
                ('prima_calculada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.empleado')),
            ],
        ),
    ]
