# Generated by Django 4.2.6 on 2024-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deducciones', '0008_prima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prima',
            name='dias_trabajados',
            field=models.IntegerField(),
        ),
    ]
