# Generated by Django 5.0.6 on 2024-06-15 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_empleados', '0008_delete_tokenaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.empleado')),
            ],
        ),
    ]
