# Generated by Django 5.0.6 on 2024-06-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], max_length=20)),
                ('nro_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('nombre1', models.CharField(max_length=255)),
                ('nombre2', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_cuenta', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tokenaccess',
            name='empleado',
        ),
        migrations.AddField(
            model_name='tokenaccess',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.administrador'),
            preserve_default=False,
        ),
    ]
