# Generated by Django 5.0.6 on 2024-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_novedad', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad'), ('permiso', 'Permiso'), ('otro', 'Otro')], help_text='Tipo de novedad', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto', max_digits=10)),
            ],
        ),
    ]
