# Generated by Django 5.0.6 on 2024-06-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nro_documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte'), ('RC', 'Registro Civil')], max_length=20)),
                ('fecha_expedicion', models.DateField()),
                ('nombre1', models.CharField(max_length=255)),
                ('nombre2', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('auxilio_transporte', models.BooleanField(default=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_identidad', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.ciudad')),
                ('rol', models.ForeignKey(default='OPERADOR', on_delete=django.db.models.deletion.CASCADE, to='gestion_empleados.rol')),
            ],
        ),
    ]
