# Generated by Django 5.0.6 on 2024-06-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0002_empleado_nivel_riesgo_empleado_salario_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('OPERADOR', 'Operador'), ('LECTOR', 'Lector')], default='GESTOR', max_length=8),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_cuenta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('INDEPENDIENTE', 'Independiente'), ('DEPENDIENTE', 'Dependiente')], default='Dependiente', max_length=13),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
