# Generated by Django 5.0.6 on 2024-06-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0003_alter_empleado_rol_empleado_estado_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(blank=True, choices=[('INDEPENDIENTE', 'Independiente'), ('DEPENDIENTE', 'Dependiente')], max_length=13, null=True),
        ),
    ]
