# Generated by Django 5.0.6 on 2024-06-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0004_alter_empleado_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado_cuenta',
            field=models.BooleanField(default=False),
        ),
    ]
