# Generated by Django 5.0.6 on 2024-06-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0006_tokenaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], max_length=20),
        ),
    ]
