# Generated by Django 5.0.6 on 2024-06-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_empleados', '0007_alter_empleado_tipo_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenAccess',
        ),
    ]
