# Generated by Django 5.0.6 on 2024-06-16 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deducciones', '0006_alter_seguridadsocial_empleado_delete_empleado'),
        ('gestion_empleados', '0008_delete_tokenaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nivel_riesgo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_gestion', to='deducciones.nivelriesgo'),
        ),
    ]
